server:
  port: '4000'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wellbe?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: wellbe
    password: wellbe#1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # 개발 시에는 update, 운영 시에는 validate 또는 none 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  web:
    resources:
      add-mappings: 'false'

logging:
  level:
    org.hibernate.SQL: debug