server:
  port: '5000'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wellbe?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: wellbe
    password: wellbe#1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # \uAC1C\uBC1C \uC2DC\uC5D0\uB294 update, \uC6B4\uC601 \uC2DC\uC5D0\uB294 validate \uB610\uB294 none \uAD8C\uC7A5
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  web:
    resources:
      add-mappings: 'false'

logging:
  level:
    org.hibernate.SQL: debug
